#ifndef ENUMS_H
#define ENUMS_H

extern const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS]; 

enum custom_keycodes {
  RGB_SLD = EZ_SAFE_RANGE,
  HSV_172_255_255,
  HSV_86_255_128,
  HSV_27_255_255,
  ST_MACRO_0,
  ST_MACRO_1,
  ST_MACRO_2,
  ST_MACRO_3,
  ST_MACRO_4,
  ST_MACRO_5,
  ST_MACRO_6,
  CSA_RSPC,
  LEFT_SC_CONTROL,
  RIGHT_SC_CONTROL,
  LAYER_TAP_MOD,
};

#endif // ENUMS_H
